// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpPkC34NV01ZramUZBb5QbP1fapQka3hE',
    appId: '1:640012319302:web:4209dbd3763e6a07a56847',
    messagingSenderId: '640012319302',
    projectId: 'social-media-app-7efc2',
    authDomain: 'social-media-app-7efc2.firebaseapp.com',
    storageBucket: 'social-media-app-7efc2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2sBgD4jSSZDK-yzwrcubBs2y2eKw5UIc',
    appId: '1:640012319302:android:7e653c361792c6e8a56847',
    messagingSenderId: '640012319302',
    projectId: 'social-media-app-7efc2',
    storageBucket: 'social-media-app-7efc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpbCUzkzfcmrTQgB3w-Xd9YTyAcOxDMoc',
    appId: '1:640012319302:ios:a09ce521759edc5ba56847',
    messagingSenderId: '640012319302',
    projectId: 'social-media-app-7efc2',
    storageBucket: 'social-media-app-7efc2.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
